{
 "title": "k33g_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "node_nodejs_eventloop_lag_stddev_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nodejs_eventloop_lag_stddev_seconds{instance=\"service-home-page:6000\",job=\"service-home-page\"}\t"
    },
    {
     "expr": "node_nodejs_eventloop_lag_seconds{instance=\"service-home-page:6000\",job=\"service-home-page\"}\t"
    }
   ]
  },
  {
   "title": "node_nodejs_external_memory_bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_nodejs_external_memory_bytes{instance=\"service-home-page:6000\",job=\"service-home-page\"}\t"
    }
   ]
  },
  {
   "title": "node_nodejs_eventloop_lag_max_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nodejs_eventloop_lag_max_seconds{instance=\"service-home-page:6000\",job=\"service-home-page\"}\t"
    }
   ]
  },
  {
   "title": "Home Page Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "home_page_counter{instance=\"service-home-page:6000\",job=\"service-home-page\"}\t"
    }
   ]
  }
 ]
}